 on:
  push:
    braches:
      - master




 jobs:
  build:
    runs-on: ubuntu-latest


    steps:
     
      - uses: actions/checkout@v3 
      
      - name: "login docker hub"
        run: docker login --username ${{ secrets.DOCKER_USRNAME }} --password ${{ secrets.DOCKER_TOKEN }}





