 on:
  push:
    braches:
      - master




 jobs:
  build:
    runs-on: ubuntu-lastest


    steps:
      - name: 'Testing Github action'
        run: pwd
      - name: 'Testing Printing'
        run: echo Ahmed






